spring:
  datasource:
    url: jdbc:sqlserver://server007.database.windows.net:1433;database=azuredb;user=simranrathore@server007;password=password@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: simranrathore
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      hbm2ddl.auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      

server:
  port: 9191